### ISSUE TITLE
Cannot run on Debian 12 bookworm

### ISSUE THREAD

**Issue by azaslavskis** [HermanKirshin/ClockReadabilityTest#1]
# Steps to reproduce: 
1. Download binary and unpack.
2. Run ClockReadabilityTest  

Expected: 
test will run

Actual behavoir:
```
./ClockReadabilityTest                                                                                      in bash at 10:09:21
./ClockReadabilityTest: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./ClockReadabilityTest)
```

SHA256 of downloaded file e34e71a30255bd6e4e1f3baa21d8e47bf6301e295b1a4781172af9ab43f73ef8

OS info: 
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```
What letting me think that is an issue with project and not machine, that if I am correct this build is self-contained, so it should take everything with it including [glibc](https://stackoverflow.com/questions/62582804/glibc-error-running-a-net-core-self-contained-executable-on-linux).

**Comment by HermanKirshin** [comment]
Thanks for the report. Looks like it is the same as [this](https://github.com/dotnet/sdk/issues/37240#issuecomment-1853407946). And I published x64 binary from Ubuntu 23. 
Now I created [another binary](https://github.com/HermanKirshin/ClockReadabilityTest/releases/download/1.0/linux-x64-older-glibc.zip) using debian 11, hope it will work now.

**Comment by alex5250** [comment]
Just for experiment could you turn off  PublishAot and send build to me. Probably can be an issue there.

**Comment by alex5250** [comment]
> Thanks for the report. Looks like it is the same as [this](https://github.com/dotnet/sdk/issues/37240#issuecomment-1853407946). And I initially published x64 binary from Ubuntu 23. Now I created [another binary](https://github.com/HermanKirshin/ClockReadabilityTest/releases/download/1.0/linux-x64-older-glibc.zip) using debian 11, hope it will work now.

![image](https://github.com/HermanKirshin/ClockReadabilityTest/assets/20460747/c651c7b0-4a7c-4162-b9b5-b5d04efbfd96)
Works thanks!
